fprintf('\n')
disp('------------------------------------------------')
disp('          Technical Parameters Test             ')
disp('------------------------------------------------')
fprintf('\n')
disp(['Persistence of AR(1)    ',num2str(rho)])
disp(['SD AR(1)                ',num2str(sigm)])
disp(['Length T AR(1)          ',num2str(T)])
disp(['Local Peak Lower        ',num2str(lpeak_low)])
disp(['Local Peak Upper        ',num2str(lpeak_up)])
disp(['Local Trough Lower      ',num2str(ltrough_low)])
disp(['Local Trough Upper      ',num2str(ltrough_up)])
fprintf('\n')
disp('------------------------------------------------')
disp('             P-Values Canova Test               ')
disp('------------------------------------------------')
fprintf('\n')
for is = 1:length(which_shock)
      disp([which_shock{is},' Shock '])
      disp('---------------------')
      for iv = 1:length(varlist)
            disp([varlist{iv},' Pvalue is ',num2str(pval(is,iv))])
      end
      fprintf('\n')
end
