function [ys_, params, info] = RBC_CME_basic_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(3)=((1/params(1)-(1-params(2)))/params(3))^(1/(params(3)-1));
    ys_(1)=ys_(3)^params(3);
    ys_(2)=ys_(1)-params(2)*ys_(3);
    ys_(6)=1/params(1);
    ys_(7)=params(6);
    ys_(4)=1;
    ys_(5)=0;
    % Auxiliary equations
    check_=0;
end
